<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='brand_filter_facet',
            new_name='brands_filter_facet',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_addtional_info',
            new_name='product_additional_info',
        ),
    ]
=======
# Generated by Django 5.0.6 on 2024-05-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='brand_filter_facet',
            new_name='brands_filter_facet',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_addtional_info',
            new_name='product_additional_info',
        ),
    ]
>>>>>>> master
