# Generated by Django 5.0.6 on 2024-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_brand_filter_facet_products_brands_filter_facet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='styleid',
            field=models.IntegerField(default=0),
        ),
    ]
