# Generated by Django 5.0.6 on 2024-05-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='accounts',
        ),
    ]
