<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_account_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='search_image',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='styleid',
            new_name='yearOfManufacture',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='account',
        ),
        migrations.RemoveField(
            model_name='products',
            name='brands_filter_facet',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_additional_info',
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='productName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
=======
# Generated by Django 5.0.6 on 2024-05-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_account_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='search_image',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='styleid',
            new_name='yearOfManufacture',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='account',
        ),
        migrations.RemoveField(
            model_name='products',
            name='brands_filter_facet',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_additional_info',
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='productName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
>>>>>>> master
