# Generated by Django 5.0.6 on 2024-05-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_shopping_cart_product_shopping_cart_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
