# Generated by Django 5.0.6 on 2024-05-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shopping_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='quantity',
        ),
    ]
