# Generated by Django 5.0.6 on 2024-05-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_shopping_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullName', models.CharField(default='', max_length=30)),
                ('address', models.TextField(default='')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('token', models.TextField(default='')),
            ],
        ),
    ]
