# Generated by Django 5.0.6 on 2024-05-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderLabel',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='totalAmount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='phoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
