# Generated by Django 5.0.6 on 2024-05-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_orderlabel_order_totalamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='firstOrderImage',
            field=models.TextField(default=''),
        ),
    ]
