# Generated by Django 5.0.6 on 2024-06-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_firstorderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=10, null=10),
            preserve_default=10,
        ),
    ]
